language: minimal
cache:
  directories:
    - $HOME/.jabba/

matrix:
  include:
    - name: "Linux JDK8"
      os: linux
      dist: xenial
      env:
        - JDK="adopt@1.8"
    - name: "Linux JDK11"
      os: linux
      dist: xenial
      env:
        - JDK="openjdk@1.11"
    - name: "Linux JDK13"
      os: linux
      dist: xenial
      env:
        - JDK="openjdk@1.13"

env:
  global:
    # Convenience variables for shortening commands
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis" 
    
before_install:
  # Check out the script set
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ant -y; fi

install:
  - WD=$PWD
  - cd ..
  - git clone https://github.com/Funz/funz-profile
  - cd $WD

script: 
  - ant test

before_deploy:
  - ant clean dist
  - cd dist; zip -r ../plugin-Python.zip *; cd ..
  - ant install
  - zip -r Funz-Python.zip Funz-Python
  
deploy:
  provider: releases
  api_key:
    secure: jI+qS6bdiRKKFbHi3R6qjURWBxjnnpD7pvvciUSeNNY9PLwSnxSiKTA14w6b5fdHTsNem/i/LmN80S6KIC/3aLkjB6rJJ6EOMca1WX+H3rUN2XFlV/ofzw4LgHNWvUN9qTIF+HiKUj1Ndj8rjUsEeIAYA26REycBUxFgfSmURnbwWF2M8MNv5bBgu1vYlFFMNBWuoz/PeioKxeRjJ1C60l9CjX2BPb98Hgm+16LotQZB2+8YRKBFpy7EwCr1aIf0RN+3/7fqZac6iYQyzzQ+WDx3HoqFSff5Qd2og8KLnRG/NV6fgBKELSMgxy9C+1a83AS8CaWh2JYCgm3bId2B8SH9IAxEdwjLPVbLEb2WTDySn3llzsdiRD3jdiWG640B4795IpV2M+pIsIRgRfcQgO0zD05WBiBO7OLzZzciu+ME4w8oitlE5gnd3mCkt4G6RbLa6Lk3gkcOXqoO0kLdzDYV7IEjovscGPh7wOL7hW00VZH7YCpN+nGme0NvJO9gzTC7HXzFEBR0AkJnTy5PRZ7BQk4PVbRJdU9Kr+ZkT5y0BXQoKfGsruMYGlJ1dwOTeUeZq5fi+wgnesg3ioQSqreMhxP9V0HGZzbRvB8JO4p3qVGWn0il1NjxXhelr+Y0RbUdCiaauonhc5mkwyGn8peBJHX3SFB6EnFa2GTTDfo=
  file_glob: true
  file:
    - Funz-*.zip
    - plugin-*.zip
  on:
    tags: true
    branch: master
  skip_cleanup: true
  overwrite: true
